---
- hosts: all
  tasks:
  - generate_metadata:
      html: "{{ lookup('file', 'metadata.xml') }}"
    register: md
    connection: local
    ignore_errors: yes

  - debug:
      msg: "{{ md.keys() }}"

  - uri:
      url: https://idp.forgeservicelab.fi/admin/metadata-converter.php?
      method: POST
      body: "xmldata={{ lookup('file', 'metadata.xml') | urlencode }}"
      HEADER_Content-Type: application/x-www-form-urlencoded
      return_content: yes
    register: result
    connection: local
    when: md | failed

  - retrieve_metadata:
      html: "{{ result.content }}"
    register: md2
    connection: local
    when: md | failed

  - shell: cat "{{ metadata_file }}" | grep -F "{{ (md2 if 'failed' in md.keys() else md).metadata.split('\n')[0] }}"
    register: grep
    ignore_errors: true
    changed_when: false

  - lineinfile:
      dest: "{{ metadata_file }}"
      line: "{{ (md2 if 'failed' in md.keys() else md).metadata }}"
      insertafter: EOF
    when: grep.rc == 1
    sudo: true
