---
- hosts: all
  tasks:
  - uri:
      url: https://idp.forgeservicelab.fi/admin/metadata-converter.php?
      method: POST
      body: "xmldata={{ lookup('file', 'metadata.xml') | urlencode }}"
      HEADER_Content-Type: application/x-www-form-urlencoded
      return_content: yes
    register: result
    connection: local

  - retrieve_metadata:
      html: "{{ result.content }}"
    register: md
    connection: local

  - shell: cat "{{ metadata_file }}" | grep -F "{{ md.metadata.split('\n')[0] }}"
    register: grep
    ignore_errors: true
    changed_when: false

  - lineinfile:
      dest: "{{ metadata_file }}"
      line: "{{ md.metadata }}"
      insertafter: EOF
    when: grep.rc == 1
    sudo: true
